/** @format */

import "@/styles/globals.css";
import Navbar from "@/components/navbar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "@/lib/utils";
import { getAuthSession } from "@/lib/auth";
import { Toaster } from "@/components/ui/toaster";
import Provider from "@/components/provider";
import type { Session } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getAuthSession();

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={cn(
          inter.className,
          "antialiased min-h-screen bg-background"
        )}
      >
        <div className="relative flex min-h-screen flex-col">
          <Provider session={session as Session}>
            <Navbar />
            <div className="container px-[16px] md:px-[2rem] max-w-7xl mx-auto h-full pt-12">
              {children}
            </div>
          </Provider>
        </div>

        <Toaster />
      </body>
    </html>
  );
}
